set_languages("go")
add_requires("brew::caddy", {alias = "caddy", optinal=true})

target("console")
    set_kind("binary")
    add_files("main.go")
    on_build(function (target)
      -- 导入配置模块
      import("core.project.config")
      local releaseDir = vformat("$(projectdir)/%s/%s/%s/%s", "target", config.plat(), config.arch(), config.mode())
      os.mkdir(releaseDir)
      os.runv("go", {"build", "-o", releaseDir})
    end)

target("wasm")
    set_kind("binary")
    add_files("main.go")
    on_build(function (target)
      -- 导入配置模块
      import("core.project.config")
      local wasm_path= vformat("$(projectdir)/%s", "web/wasm/main.wasm")
      os.setenv("GOOS", "js")
      os.setenv("GOARCH", "wasm")
      os.runv("go", {"build", "-o", wasm_path})
    end)

target("server")
    add_deps("wasm")
    on_run(function () 
        local web_dir = vformat("$(projectdir)/%s", "web")
        local caddy_conf = vformat("$(projectdir)/%s", "config/Caddyfile")
        os.runv("sudo", {"caddy","run", "--config", caddy_conf})
    end)
